version: 2

sources:
  - name: ext_src
    database: dbt_training
    schema: raw
    tables:
      - name: 'employees'

models:
  - name: hoge
    description: '{{ doc("table_hoge") }}'
    columns:
      - name: fuga
        tests:
          - unique
          - not_null
          - accepted_values:
              values: ['101', '102','103','104','105']
          - relationships:
              to: source('ext_src','employees')
              field: employee_id
          - my_not_null
  - name: ref_hoge
    description: '日本語'
